### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by tysmmsy** [tysmmsy/furima_28102#9]
## 自身のフリマアプリのURL   
 https://furima-28102.herokuapp.com

##  Basic認証のIDとパスワード
ID: admin
PASS: 2222

##  出品者用のメールアドレスとパスワード
 本番環境にて商品出品しているユーザーの情報
MAIL: test11@test.com
PASS: aaa111
## 購入者用のメールアドレスとパスワード 
上記とは異なる、本番 環境で使用可能なユーザーの情報
MAIL: test10@test.com 
PASS: aaa111

## PAY.JPのテストカード情報
購入用カードの番号: 4242424242424242
期限: 12/24
セキュリティコード: 123

よろしくお願いいたします。

**Comment by eeee-0000** [comment]
tysmmsyさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
